name: minecraft
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

env:
  REGISTRY: ghcr.io
  

jobs:
  build-vanilla:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/minecraft
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          ./build-minecraft.sh
  build-paper:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/paper
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          ./build-paper.sh
  build-velocity:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/velocity
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          ./build-velocity.sh