name: minecraft-parallel
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      latest: steps.versions.outputs.latest
      versions: steps.versions.outputs.versions
    steps:
      - uses: actions/checkout@v3
      - name: Get Minecraft Releases
        id: versions
        run: ./minecraft/build/get-minecraft-versions.sh

  debug-output:
    needs: get-versions
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.get-versions.outputs.latest }}
      - run: echo ${{ needs.get-versions.outputs.versions }}

  build-vanilla:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/minecraft
      LATEST_VERSION: ${{ needs.get-versions.outputs.latest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build
        run: ./minecraft/build/build-version.sh