name: paper-parallel
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  get-versions:
    name: Get Paper Releases
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.versions.outputs.latest }}
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Paper Releases
        id: versions
        run: ./paper/build/get-versions.sh

  build-paper:
    name: Build Paper ${{ matrix.version }}
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/paper
      LATEST_VERSION: ${{ needs.get-versions.outputs.latest }}
      VERSION: ${{ toJSON(matrix.version) }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./paper/build/build-version.sh