name: Paper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  pull_request:
    paths:
      - .github/actions
      - .github/workflows/paper-parallel.yaml
      - paper
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  get-versions:
    name: Get Paper Releases
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.versions.outputs.latest }}
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Paper Releases
        id: versions
        run: ./paper/build/get-versions.sh

  build-paper:
    name: Build Paper ${{ matrix.version }}
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/paper
      LATEST_VERSION: ${{ needs.get-versions.outputs.latest }}
      VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v3

      # Normalize our Image name and Update our ENV
      - name: Normalize Image Name
        uses: ./.github/actions/normalize-image-name
        id: normalize-image-name
        with:
          image-name: ${{ env.IMAGE_NAME }}
      - name: Update Image Name
        run: echo "IMAGE_NAME=${{ steps.normalize-image-name.outputs.image-name }}" >> "$GITHUB_ENV"

      - name: Get Build Info
        id: build-info
        run: ./paper/build/build-version.sh

      - name: Build Latest
        uses: ./.github/actions/build-and-deploy
        with:
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          context: paper
          image-name: ${{ env.IMAGE_NAME }}
          version: ${{ steps.build-info.outputs.minecraft-version }}
          latest-version: ${{ env.LATEST_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.build-info.outputs.minecraft-version }}
            ${{ env.IMAGE_NAME }}:${{ steps.build-info.outputs.version }}
          build-args: |
            MINECRAFT_VERSION=${{ steps.build-info.outputs.minecraft-version }}
            BUILD_NUMBER=${{ steps.build-info.outputs.build-id }}
