name: Purpur
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  get-versions:
    name: Get Purpur Releases
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.versions.outputs.latest }}
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Purpur Releases
        id: versions
        run: ./purpur/build/get-versions.sh

  build-purpur:
    name: Build Purpur ${{ matrix.version }}
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/purpur
      LATEST_VERSION: ${{ needs.get-versions.outputs.latest }}
      VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Normalize our Image name and Update our ENV
      - name: Normalize Image Name
        uses: ./.github/actions/normalize-image-name
        id: normalize-image-name
        with:
          image-name: ${{ env.IMAGE_NAME }}
      - name: Update Image Name
        run: echo "IMAGE_NAME=${{ steps.normalize-image-name.outputs.image-name }}" >> "$GITHUB_ENV"
      - name: Build
        run: ./purpur/build/build-version.sh
